use_frameworks!

platform :ios, '8.0'

target 'XinCanCategoryKit_Example' do
  pod 'XinCanCategoryKit', :path => '../'

  target 'XinCanCategoryKit_Tests' do
    inherit! :search_paths

    
  end
end
